version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: guardrail-frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: guardrail-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@guardrail-db:5432/guardrail_db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: guardrail-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guardrail_db
    ports:
      - "5433:5432"
    volumes:
      - guardrail_data:/var/lib/postgresql/data

volumes:
  guardrail_data: