services:
  frontend:
    build: ./frontend
    container_name: guardrail-frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: guardrail-backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      # ✅ use consistent DB var with your code & Dockerfile
      - GUARDRAILS_DB_URL=postgresql://postgres:postgres@guardrail-db:5432/guardrails
    ports:
      - "8080:8080"
    depends_on:
      - guardrail-db
    command: >
      sh -c "npx prisma migrate deploy && node dist/index.js"

  guardrail-db:
    image: postgres:15
    container_name: guardrail-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guardrails
    ports:
      - "5433:5432"
    volumes:
      - guardrail_data:/var/lib/postgresql/data

volumes:
  guardrail_data: